mongoid_options: &mongoid_options
  # Includes the root model name in json serialization. (default: false)
  # include_root_in_json: false

  # Include the _type field in serialization. (default: false)
  # include_type_for_serialization: false

  # Preload all models in development, needed when models use
  # inheritance. (default: false)
  preload_models: true

  # Raise an error when performing a #find and the document is not found.
  # (default: true)
  # raise_not_found_error: true

  # Raise an error when defining a scope with the same name as an
  # existing method. (default: false)
  scope_overwrite_exception: true

  # Use Active Support's time zone in conversions. (default: true)
  # use_activesupport_time_zone: true

  # Ensure all times are UTC in the app side. (default: false)
  use_utc: true

development:
  clients:
    default: &default_development
      database: rocketjob_development
      hosts:
        - mongo
      options:
        read:
          mode: :primary
        write:
          w:   0
        max_pool_size: 5
        min_pool_size: 1
    rocketjob:
      <<: *default_development
    rocketjob_slices:
      <<: *default_development
  options:
    <<: *mongoid_options
